const schools=[
{name:'서울대학교',region:'서울',seats:150,cut:144,prestige:1.18},{name:'고려대학교',region:'서울',seats:120,cut:140,prestige:1.14},{name:'연세대학교',region:'서울',seats:120,cut:139,prestige:1.13},{name:'성균관대학교',region:'서울',seats:120,cut:136,prestige:1.08},{name:'한양대학교',region:'서울',seats:100,cut:134,prestige:1.05},{name:'이화여자대학교',region:'서울',seats:100,cut:132,prestige:1.03},{name:'서강대학교',region:'서울',seats:40,cut:134,prestige:1.04},{name:'중앙대학교',region:'서울',seats:50,cut:131,prestige:1.00},{name:'경희대학교',region:'서울',seats:60,cut:130,prestige:.99},{name:'서울시립대학교',region:'서울',seats:50,cut:132,prestige:1.01},{name:'한국외국어대학교',region:'서울',seats:50,cut:129,prestige:.98},{name:'건국대학교',region:'서울',seats:40,cut:128,prestige:.96},{name:'아주대학교',region:'경기',seats:50,cut:127,prestige:.94},{name:'인하대학교',region:'인천',seats:50,cut:126,prestige:.93},{name:'부산대학교',region:'부산',seats:120,cut:128,prestige:.95},{name:'경북대학교',region:'대구',seats:120,cut:127,prestige:.94},{name:'전남대학교',region:'광주',seats:120,cut:125,prestige:.91},{name:'전북대학교',region:'전북',seats:80,cut:123,prestige:.89},{name:'충남대학교',region:'대전',seats:100,cut:125,prestige:.91},{name:'충북대학교',region:'충북',seats:70,cut:122,prestige:.88},{name:'강원대학교',region:'강원',seats:40,cut:119,prestige:.85},{name:'제주대학교',region:'제주',seats:40,cut:117,prestige:.83},{name:'영남대학교',region:'대구',seats:70,cut:121,prestige:.87},{name:'동아대학교',region:'부산',seats:80,cut:120,prestige:.86},{name:'원광대학교',region:'전북',seats:60,cut:118,prestige:.84}
];
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const els={gpa:$('#gpa'),leet:$('#leet'),english:$('#english'),soft:$('#soft'),university:$('#university'),memo:$('#memo'),sim:$('#simLeet')};
let filter='all';
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function state(){return{gpa:+els.gpa.value,leet:+els.leet.value,english:+els.english.value,soft:+els.soft.value,uni:+els.university.value,memo:els.memo.value}}
function competitiveness(s){const g=clamp((s.gpa-2.5)/2,0,1)*26,l=clamp((s.leet-95)/60,0,1)*46,e=clamp((s.english-600)/390,0,1)*10,u=s.uni*10,soft=s.soft/5*8;return{g,l,e,u,soft,total:clamp(g+l+e+u+soft,0,100)}}
function probability(s,school,leetOverride){const leet=leetOverride??s.leet;const z=(leet-school.cut)*.13+(s.gpa-3.5)*2.2+(s.english-850)/180+(s.uni-.75)*2.2+(s.soft-3)*.3-(school.prestige-1)*2.2;return Math.round(clamp(100/(1+Math.exp(-z)),3,97))}
function band(p){return p>=70?'safe':p>=40?'target':'reach'}
function render(){const s=state(),c=competitiveness(s);$('#gpaValue').textContent=`${s.gpa.toFixed(2)} / 4.5`;$('#leetValue').textContent=s.leet;$('#englishValue').textContent=s.english;$('#softValue').textContent=['매우 낮음','낮음','보통 이상','높음','매우 높음'][s.soft-1];$('#heroLeet').textContent=s.leet;$('#heroGpa').textContent=s.gpa.toFixed(2);$('#heroEnglish').textContent=s.english;$('#heroScore').textContent=`상위 ${Math.max(3,Math.round(100-c.total))}%`;$('#gaugeText').textContent=Math.round(c.total);$('.gauge').style.background=`conic-gradient(var(--brand) 0 ${c.total}%,#eceafc ${c.total}%)`;$('#totalScore').textContent=`${Math.round(c.total)}점`;$('#tierBadge').textContent=c.total>=82?'최상위권 경쟁 가능':c.total>=70?'상위권 도전 가능':c.total>=58?'중상위권 적정':'기초 경쟁력 보완 필요';
 const bars=[['GPA',c.g,26],['LEET',c.l,46],['영어',c.e,10],['대학·정성',c.u+c.soft,18]];$('#scoreBars').innerHTML=bars.map(([n,v,m])=>`<div class="bar-item"><div class="bar-label"><span>${n}</span><b>${Math.round(v/m*100)}%</b></div><div class="bar-track"><div class="bar-fill" style="width:${v/m*100}%"></div></div></div>`).join('');
 const leetGap=135-s.leet,gpaStrong=s.gpa>=3.8;$('#mainAdvice').innerHTML=gpaStrong&&leetGap>0?`GPA는 경쟁력이 높습니다. LEET를 <b>${Math.max(3,leetGap)}점</b> 높이면 상위권 학교의 적정 지원 범위가 크게 넓어집니다.`:s.leet>=135?`LEET 경쟁력이 좋습니다. 자기소개서와 면접에서 <b>학업·진로의 일관성</b>을 강화하세요.`:`현재는 LEET 개선 효과가 가장 큽니다. 지원군은 안정 2, 적정 3, 소신 1의 조합을 권합니다.`;
 $('#leverageText').textContent=s.leet<135?`LEET를 3점 올리는 것이 가장 효율적입니다. 현재 조건에서 주요 학교 평균 합격 가능성이 약 ${delta(s,3).toFixed(1)}%p 상승합니다.`:s.gpa<3.8?'학점 보완이 가능한 시기라면 GPA 관리가 최우선입니다.':'정량 요소가 충분하므로 면접·자기소개서의 완성도가 당락을 가를 가능성이 큽니다.';
 renderSchools();renderPortfolio(s);updateSim();localStorage.setItem('lawready-state',JSON.stringify(s));}
function renderSchools(){const s=state(),q=$('#search').value.trim(),sort=$('#sort').value;let list=schools.map(x=>({...x,p:probability(s,x)})).filter(x=>(filter==='all'||band(x.p)===filter)&&x.name.includes(q));list.sort(sort==='name'?(a,b)=>a.name.localeCompare(b.name):sort==='seats'?(a,b)=>b.seats-a.seats:(a,b)=>b.p-a.p);$('#schoolGrid').innerHTML=list.map(x=>`<article class="school-card"><div class="school-top"><div><h3>${x.name}</h3><small>${x.region} · 정원 ${x.seats}명</small></div><span class="risk ${band(x.p)}">${{safe:'안정',target:'적정',reach:'소신'}[band(x.p)]}</span></div><div class="meter"><div style="width:${x.p}%"></div></div><div class="school-meta"><span>예상 합격 가능성</span><span class="prob">${x.p}%</span></div></article>`).join('')||'<p>조건에 맞는 학교가 없습니다.</p>'}
function delta(s,n){return schools.reduce((a,x)=>a+probability(s,x,s.leet+n)-probability(s,x),0)/schools.length}
function renderPortfolio(s){const ranked=schools.map(x=>({...x,p:probability(s,x)}));const pick=(lo,hi)=>ranked.filter(x=>x.p>=lo&&x.p<hi).sort((a,b)=>b.p-a.p).slice(0,2).map(x=>x.name.replace('대학교','대')).join(', ');$('#portfolioText').textContent=`안정: ${pick(70,101)||'지역권 로스쿨'} / 적정: ${pick(40,70)||'중위권 로스쿨'} / 소신: ${pick(15,40)||'상위권 1개교'} 조합이 적절합니다.`}
function updateSim(){const s=state(),target=+els.sim.value;$('#simValue').textContent=target;const d=schools.reduce((a,x)=>a+probability(s,x,target)-probability(s,x),0)/schools.length;$('#simDelta').textContent=`${d>=0?'+':''}${d.toFixed(1)}%p`}
Object.values(els).forEach(el=>el.addEventListener('input',render));$('#search').addEventListener('input',renderSchools);$('#sort').addEventListener('change',renderSchools);els.sim.addEventListener('input',updateSim);$$('.chip').forEach(b=>b.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderSchools()});
$('#saveBtn').onclick=()=>{const data=JSON.parse(localStorage.getItem('lawready-history')||'[]');data.unshift({...state(),date:new Date().toLocaleString('ko-KR')});localStorage.setItem('lawready-history',JSON.stringify(data.slice(0,10)));toast('현재 결과가 저장되었습니다.')};$('#resetBtn').onclick=()=>{localStorage.removeItem('lawready-state');Object.assign(els.gpa,{value:3.95});els.leet.value=130;els.english.value=950;els.soft.value=3;els.university.selectedIndex=1;els.memo.value='';els.sim.value=133;render();toast('입력값을 초기화했습니다.')};function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
try{const s=JSON.parse(localStorage.getItem('lawready-state'));if(s){els.gpa.value=s.gpa;els.leet.value=s.leet;els.english.value=s.english;els.soft.value=s.soft;els.university.value=s.uni;els.memo.value=s.memo||'';els.sim.value=s.leet+3}}catch(e){}render();
